import { Retention } from './retention';
import { useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, BookOpen, Check, Code2, FilePlus2, FlaskConical, Plus, ShieldCheck, X } from 'lucide-react';
import { api, date, post, type Mapping, type Policy, type RecordItem } from './api';
import { Badge, Empty, ErrorBox, Loading, PageHead, moveTab, type Context } from './components';

const freshMapping: Mapping = {
  name: '', vendor: 'unknown', firmware: 'unknown', fact: 'ssh_version', selector_type: 'line_prefix',
  selector: 'secure-shell-version', scope_prefix: '', value_mode: 'last_token', value_type: 'integer',
  literal: null, description: '', cases: [
    { text: 'secure-shell-version 2', expected: 2, label_source: 'Synthetic example; reviewer must validate' },
    { text: 'secure-shell-version 1', expected: 1, label_source: 'Synthetic example; reviewer must validate' },
    { text: 'unrelated-setting enabled', expected: null, label_source: 'Synthetic no-match example' },
  ],
};
function useRecords(kind: string) {
  const [offset, setOffset] = useState(0);
  const query = useQuery({ queryKey: [kind, offset], queryFn: () => api<{ items: RecordItem[]; total: number }>(`/records?kind=${kind}&offset=${offset}&page_size=30`) });
  const total = query.data?.total ?? 0;
  return { ...query, pager: <div className="pagination"><span>{total ? offset + 1 : 0} - {Math.min(offset + 30, total)} of {total}</span><div><button className="button text" disabled={!offset || query.isFetching} onClick={() => setOffset(offset - 30)}>Previous</button><button className="button text" disabled={offset + 30 >= total || query.isFetching} onClick={() => setOffset(offset + 30)}>Next</button></div></div> };
}

export function Training(ctx: Context) {
  const query = useRecords('mapping');
  const client = useQueryClient();
  const [selected, setSelected] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState<Mapping>(structuredClone(freshMapping));
  const [expected, setExpected] = useState(['2', '1', 'null']);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const row = query.data?.items.find(item => item.id === selected) ?? query.data?.items[0];
  const spec = row?.spec as Mapping | undefined;
  function edit(mapping: Mapping) { setForm(structuredClone(mapping)); setExpected(mapping.cases.map(item => JSON.stringify(item.expected))); setError(null); setEditing(true); }
  async function save(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(null);
    try {
      const payload = { ...form, cases: form.cases.map((item, index) => ({ ...item, expected: JSON.parse(expected[index]) })) };
      const result = await post<RecordItem>('/mappings', payload); setSelected(result.id); setEditing(false);
      await client.invalidateQueries({ queryKey: ['mapping'] }); ctx.notify('Mapping draft created. Test evidence must be reviewed before activation.');
    } catch (e) { setError(e); } finally { setBusy(false); }
  }
  async function action(name: string) { setBusy(true); try { await post(`/mappings/${row!.id}/${name}`); await client.invalidateQueries({ queryKey: ['mapping'] }); ctx.notify(name === 'activate' ? 'Mapping activated. New audits can use this version.' : 'Mapping updated.'); } catch (e) { ctx.notify((e as Error).message, true); } finally { setBusy(false); } }
  return <><PageHead title="Training & review" description="Teach a format, test its meaning, and approve a version your audits can rely on."><button className="button" onClick={() => edit(freshMapping)} disabled={!ctx.user.roles.includes('auditor')}><Plus size={17} /> New mapping</button></PageHead>
    {editing && <form className="surface mapping-form" onSubmit={save}><div className="section-head"><h2>Propose a mapping</h2><button type="button" className="icon-button" aria-label="Close mapping editor" onClick={() => setEditing(false)}><X size={18} /></button></div><div className="form-body"><ErrorBox error={error} />
      <div className="form-grid"><label>Mapping name<input required minLength={3} maxLength={120} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="SSH version in an unfamiliar format" /></label><label>Baseline fact<input required value={form.fact} onChange={event => setForm({ ...form, fact: event.target.value })} /></label><label>Vendor / format identifier<input required value={form.vendor} onChange={event => setForm({ ...form, vendor: event.target.value })} /></label><label>Exact firmware scope<input required value={form.firmware} onChange={event => setForm({ ...form, firmware: event.target.value })} /></label>
      <label>Selector type<select value={form.selector_type} onChange={event => setForm({ ...form, selector_type: event.target.value, value_mode: event.target.value === 'line_prefix' ? 'last_token' : 'selected' })}><option value="line_prefix">Command prefix</option><option value="json_path">JSON object path</option><option value="xml_path">XML element path</option></select></label><label>Selector<input required value={form.selector} onChange={event => setForm({ ...form, selector: event.target.value })} /></label><label>Value type<select value={form.value_type} onChange={event => setForm({ ...form, value_type: event.target.value })}><option value="integer">Integer</option><option value="boolean">Boolean</option><option value="string">Text</option></select></label><label>Value extraction<select value={form.value_mode} onChange={event => setForm({ ...form, value_mode: event.target.value })}><option value="last_token">Last command token</option><option value="selected">Selected value</option><option value="literal">Constant value</option></select></label>
      {form.value_mode === 'literal' && <label>Constant value<input required value={String(form.literal ?? '')} onChange={event => setForm({ ...form, literal: event.target.value })} /></label>}<label>Command scope prefix (optional)<input value={form.scope_prefix} onChange={event => setForm({ ...form, scope_prefix: event.target.value })} /></label></div>
      <label>Evidence and interpretation<textarea rows={3} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Explain the source, firmware behavior, and boundaries of this mapping." /></label>
      <div className="section-head compact"><h3>Validation cases</h3><button type="button" className="button text" disabled={form.cases.length >= 30} onClick={() => { setForm({ ...form, cases: [...form.cases, { text: '', expected: null, label_source: 'Reviewer supplied' }] }); setExpected([...expected, 'null']); }}>Add case</button></div><p className="muted">Include at least three distinct cases and a non-match. The initial examples below are synthetic; replace them with evidence for your format. Use JSON values: 2, true, "text", or null for no match.</p>
      {form.cases.map((item, index) => <div className="test-case" key={index}><label>Case {index + 1} configuration<textarea className="mono" required rows={3} value={item.text} onChange={event => setForm({ ...form, cases: form.cases.map((current, number) => number === index ? { ...current, text: event.target.value } : current) })} /></label><label>Expected value (JSON)<input className="mono" required value={expected[index]} onChange={event => setExpected(expected.map((value, number) => number === index ? event.target.value : value))} /></label></div>)}
      <button className="button" disabled={busy}>{busy ? 'Testing and saving…' : 'Test and save draft'} <ArrowRight size={16} /></button></div></form>}
    <ErrorBox error={query.error} />{query.pager}{query.isError ? null : query.isPending ? <Loading /> : !query.data?.items.length ? <section className="surface"><Empty title="Your learning library starts here"><p>A mapping defines what a command means. Its tests and approval determine when an audit may use that meaning.</p><button className="button secondary" disabled={!ctx.user.roles.includes('auditor')} onClick={() => edit(freshMapping)}><FlaskConical size={16} /> Propose your first mapping</button></Empty></section> : <div className="library-layout"><section className="surface library-list"><div className="section-head"><h2>Mapping versions</h2><span className="muted">{query.data.total}</span></div>{query.data.items.map(item => <button className={row?.id === item.id ? 'library-row selected' : 'library-row'} key={item.id} aria-pressed={row?.id === item.id} onClick={() => setSelected(item.id)}><strong>{item.name}</strong><small>{(item.spec as Mapping).vendor} · {(item.spec as Mapping).firmware}</small><Badge value={item.status ?? 'draft'} /></button>)}</section><section className="surface library-detail"><div className="section-head"><h2>{row!.name}</h2><Badge value={row!.status ?? 'draft'} /></div><div className="form-body"><dl className="detail-grid"><div><dt>Fact</dt><dd className="mono">{spec!.fact}</dd></div><div><dt>Version</dt><dd className="mono">{row!.version}</dd></div><div><dt>Vendor / firmware</dt><dd>{spec!.vendor} / {spec!.firmware}</dd></div><div><dt>Selector</dt><dd className="mono">{spec!.selector}</dd></div><div><dt>Selector type / scope</dt><dd>{spec!.selector_type} / {spec!.scope_prefix || 'Device / root'}</dd></div><div><dt>Extraction / value type</dt><dd>{spec!.value_mode} / {spec!.value_type}</dd></div>{spec!.value_mode === 'literal' && <div><dt>Constant value</dt><dd>{JSON.stringify(spec!.literal)}</dd></div>}</dl><p>{spec!.description || 'No interpretation notes were supplied.'}</p><h3>Test evidence</h3><p className="muted">Passing these cases validates this declared test set. Reviewer judgment and independently sourced cases remain necessary.</p>{spec!.cases.map((item, index) => <details className="case-result" key={index}><summary><Badge value={row!.tests?.results[index]?.passed ? 'pass' : 'fail'} /> Case {index + 1}<span>Expected {JSON.stringify(item.expected)}</span></summary><pre>{item.text}</pre><p>Observed: {JSON.stringify(row!.tests?.results[index]?.actual)} · {item.label_source}</p></details>)}
      <div className="actions wrap"><button className="button secondary" disabled={busy || !ctx.user.roles.includes('auditor')} onClick={() => action('test')}><FlaskConical size={16} /> Run tests</button><button className="button secondary" disabled={!ctx.user.roles.includes('auditor')} onClick={() => edit(spec!)}>Edit as new version</button>{ctx.user.roles.includes('reviewer') && (row!.status === 'approved' ? <button className="button text" disabled={busy} onClick={() => action('retire')}>Retire mapping</button> : <button className="button" disabled={busy || !row!.tests?.passed} onClick={() => action('activate')}><Check size={16} /> Review complete — activate</button>)}</div></div></section></div>}
  </>;
}

export function Policies(ctx: Context) {
  const query = useQuery({ queryKey: ['policies'], queryFn: () => api<{ items: Policy[] }>('/policies') });
  const imported = useRecords('policy');
  const client = useQueryClient();
  const [selected, setSelected] = useState(0);
  const [draft, setDraft] = useState('');
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState<unknown>(null);
  async function save(event: FormEvent) { event.preventDefault(); setError(null); try { await post('/policies', JSON.parse(draft)); await client.invalidateQueries({ queryKey: ['policy'] }); setEditing(false); ctx.notify('Reviewed policy version imported.'); } catch (e) { setError(e); } }
  const policy = query.data?.items[selected];
  return <><PageHead title="Policy library" description="Declared technical checks, exact versions, and source-backed framework crosswalks."><button className="button" disabled={!ctx.user.roles.includes('reviewer') || !policy} onClick={() => { setDraft(JSON.stringify(policy, null, 2)); setEditing(true); }}><FilePlus2 size={16} /> Import reviewed policy</button></PageHead>
    <div className="notice"><ShieldCheck size={18} /> Included packs are team-authored technical baselines with illustrative crosswalks, not official benchmark releases or full-framework certification.</div>
    {editing && <form className="surface form-body" onSubmit={save}><h2>Reviewed policy JSON</h2><p>Supply the exact scope, version, source references, typed rules and vendor-specific remediation. Importing records your reviewer approval.</p><ErrorBox error={error} /><label>Policy definition<textarea className="mono" rows={18} required value={draft} onChange={event => setDraft(event.target.value)} /></label><div className="actions"><button className="button">Import reviewed version</button><button type="button" className="button text" onClick={() => setEditing(false)}>Cancel</button></div></form>}
    <ErrorBox error={query.error} />{query.isError ? null : query.isPending ? <Loading /> : policy && <section className="surface"><div className="tabs padded" role="tablist" aria-label="Framework packs" onKeyDown={moveTab}>{query.data!.items.map((item, index) => <button role="tab" id={`policy-tab-${index}`} aria-controls="policy-panel" tabIndex={selected === index ? 0 : -1} aria-selected={selected === index} className={selected === index ? 'selected' : ''} key={item.framework} onClick={() => setSelected(index)}>{item.framework}</button>)}</div><div role="tabpanel" id="policy-panel" aria-labelledby={`policy-tab-${selected}`} className="form-body"><h2>{policy.name}</h2><p>{policy.scope}</p><small className="mono">Version {policy.version} · {policy.rules.length} technical checks</small></div><div className="table-scroll" role="region" aria-label="Scrollable records table" tabIndex={0}><table><thead><tr><th>Control</th><th>Technical check</th><th>Expected fact</th><th>Severity</th></tr></thead><tbody>{(policy.rules as { id: string; title: string; fact: string; expected: unknown; severity: string }[]).map(rule => <tr key={rule.id}><td className="mono">{rule.id}</td><td>{rule.title}</td><td><code>{rule.fact}</code><small>{JSON.stringify(rule.expected)}</small></td><td><Badge value={rule.severity} /></td></tr>)}</tbody></table></div></section>}
    <section className="surface"><div className="section-head"><h2>Imported policy versions</h2></div>{imported.pager}<ErrorBox error={imported.error} />{imported.isError ? null : imported.isPending ? <Loading /> : imported.data?.items.length ? imported.data.items.map(item => <div className="source-row" key={item.id}><BookOpen size={20} /><div><h3>{item.name}</h3><p>{(item.spec as Policy).version} · {(item.spec as Policy).scope}</p><small className="mono">Policy ID: {item.id}</small></div><Badge value="approved" /></div>) : <p className="form-body muted">No reviewed policy imports yet. Exact editions and source material can be added as your coverage grows.</p>}</section>
  </>;
}

export function Sources(ctx: Context) {
  const query = useRecords('source');
  const client = useQueryClient();
  const [editing, setEditing] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const [form, setForm] = useState({ name: '', authority: '', version: '', url: '', permission: '', content: '' });
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await post('/sources', form); await client.invalidateQueries({ queryKey: ['source'] }); setEditing(false); ctx.notify('Reference registered with its version and content hash.'); } catch (e) { setError(e); } finally { setBusy(false); } }
  return <><PageHead title="Reference sources" description="A versioned collection for rule interpretation and agent investigation."><button className="button" disabled={!ctx.user.roles.includes('reviewer')} onClick={() => setEditing(!editing)}><Plus size={17} /> Register reference</button></PageHead>
    <div className="context-strip"><BookOpen size={18} /><p>The organizer listed NCIIPC, CIS, NIST, DISA STIGs, ISO/IEC 27001 and vendor documentation as references. No downloadable dataset was supplied.</p></div>
    {editing && <form className="surface form-body" onSubmit={save}><h2>Register an authorized reference</h2><ErrorBox error={error} /><div className="form-grid">{[['name', 'Document title'], ['authority', 'Authority / vendor'], ['version', 'Edition / release'], ['url', 'Source URL (optional)'], ['permission', 'Permission or licensing basis']].map(([key, label]) => <label key={key}>{label}<input required={key !== 'url'} type={key === 'url' ? 'url' : 'text'} value={form[key as keyof typeof form]} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><label>Authorized reference text<textarea required rows={12} maxLength={200000} value={form.content} onChange={event => setForm({ ...form, content: event.target.value })} placeholder="Paste the relevant source passages. Preserve control identifiers and vendor/version context." /></label><p className="muted">The source URL is recorded for provenance. The application does not automatically fetch it or execute embedded instructions.</p><button className="button" disabled={busy}>{busy ? 'Registering…' : 'Register reviewed reference'}</button></form>}
    {query.pager}<section className="surface"><div className="section-head"><h2>Approved collection</h2><span className="muted">{query.data?.total ?? 0} sources</span></div><ErrorBox error={query.error} />{query.isError ? null : query.isPending ? <Loading /> : query.data?.items.length ? query.data.items.map(item => <details className="reference-detail" key={item.id}><summary><BookOpen size={20} /><div><strong>{item.name}</strong><small>{item.authority} · {item.version}</small></div><Badge value="approved" /></summary><div className="form-body">{item.url && /^https?:\/\//.test(item.url) && <a href={item.url} target="_blank" rel="noreferrer">Open source reference ↗</a>}<pre className="reference-text">{item.content}</pre></div></details>) : <Empty title="Keep the source of every rule"><p>Register the exact standard edition or vendor documentation that supports your interpretation.</p></Empty>}</section>
  </>;
}

export function Administration(ctx: Context) {
  const events = useQuery({ queryKey: ['events'], enabled: ctx.user.roles.includes('admin'), queryFn: () => api<{ items: { id: string; action: string; actor: string; target: string; at: string }[] }>('/events') });
  return <><PageHead title="Activity & settings" description="Workspace access, provider configuration, and the actions behind your audit history." />
    <div className="settings-layout"><section className="surface form-body"><div className="setting-title"><ShieldCheck size={20} /><h2>Workspace access</h2></div><dl className="detail-grid"><div><dt>Signed in as</dt><dd>{ctx.user.name}</dd></div><div><dt>Organization</dt><dd>{ctx.user.workspace}</dd></div><div><dt>Assigned roles</dt><dd>{ctx.user.roles.join(', ')}</dd></div></dl><p className="muted">Accounts and roles are managed by the local identity service. API access and stored records are scoped to your organization.</p></section>
    <section className="surface form-body"><div className="setting-title"><Code2 size={20} /><h2>Gemini integration</h2><Badge value={ctx.user.ai.configured ? 'configured' : 'not_configured'} /></div><dl className="detail-grid"><div><dt>Selected model</dt><dd>{ctx.user.ai.model ?? 'Not configured'}</dd></div><div><dt>Inference</dt><dd>{ctx.user.ai.enabled ? 'Enabled' : 'Disabled'}</dd></div></dl><p className="muted">Set GEMINI_API_KEY and GEMINI_MODEL in the project’s .env file. Enable LLM_ENABLED and restart the API and worker. Secrets are never entered into this browser interface.</p><p>Deterministic audits and stored reports work independently of Gemini.</p></section></div>
    <Retention {...ctx} /><section className="surface"><div className="section-head"><h2>Recent workspace activity</h2><span className="muted">Latest 100 events</span></div><ErrorBox error={events.error} />{!ctx.user.roles.includes('admin') ? <p className="form-body">The administrator role is required to view workspace activity.</p> : events.isPending ? <Loading /> : events.data?.items.length ? <div className="table-scroll" role="region" aria-label="Scrollable records table" tabIndex={0}><table><thead><tr><th>Action</th><th>Record</th><th>Actor</th><th>Time</th></tr></thead><tbody>{events.data.items.map(item => <tr key={item.id}><td>{item.action.replaceAll('.', ' / ')}</td><td className="mono">{item.target.slice(0, 12)}</td><td className="mono">{item.actor.slice(0, 12)}</td><td>{date(item.at)}</td></tr>)}</tbody></table></div> : <Empty title="Activity will appear here"><p>Uploads, reviews, exports and session changes are recorded as they occur.</p></Empty>}</section>
  </>;
}
